export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_UNSUCCESSFUL = 'ADD_POST_UNSUCCESSFUL'
export const ADD_POST_FAILED = 'ADD_POST_FAILED'

export const PREDICT_PRICE_SUCCESS = 'PREDICT_PRICE_SUCCESS'
export const PREDICT_PRICE_UNSUCCESSFUL = 'PREDICT_PRICE_UNSUCCESSFUL'
export const PREDICT_PRICE_FAILED = 'PREDICT_PRICE_FAILED'